### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by dpaola2** [keithprickett/lacrosse_to_wunderground#2]
Just wanted to say thanks. I stumbled upon this python library while researching the La Crosse sensors that I found on craigslist. I ended up porting your library into some [ruby interactors](https://github.com/collectiveidea/interactor) and [built them into a Rails app](https://github.com/dpaola2/WeatherStation) that lets me save and monitor and have a simple homepage.

You saved me a lot of time!

**Comment by keithprickett** [comment]
I'm glad I could help!  This was a fun project to hack at and it's good to see that it's helpful to someone other than myself.
